
- name: Copy file node exporter file
  copy:
    src: node_exporter-{{ version }}/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: 0755
  vars:
    #version: 0.18.1
    version: 1.0.0-rc.0


- name: Copy file node exporter service file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/




